project_id = "pywdwanqlynoatyesegb"

[functions.generate-lyrics]
verify_jwt = false

[functions.generate-music]
verify_jwt = false

[functions.suno-callback]
verify_jwt = false

[functions.extract-document]
verify_jwt = false

[functions.generate-quiz]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false