import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Download, FileArchive, Loader2, Music, CheckCircle, ArrowLeft, BookOpen } from "lucide-react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { useAuth } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { usePageSEO } from "@/hooks/usePageSEO";
import JSZip from "jszip";

const ease = [0.25, 0.46, 0.45, 0.94] as [number, number, number, number];

interface Song {
  id: string;
  title: string;
  style: string;
  original_text: string;
  generated_lyrics: string | null;
  status: string;
  subject: string | null;
}

function escapeXml(str: string): string {
  return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&apos;");
}

function escapeHtml(str: string): string {
  return str.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

function generateSCORMManifest(song: Song) {
  const safeTitle = escapeXml(song.title);
  return `<?xml version="1.0" encoding="UTF-8"?>
<manifest identifier="studybeats-${song.id}" version="1.0"
  xmlns="http://www.imsproject.org/xsd/imscp_rootv1p1p2"
  xmlns:adlcp="http://www.adlnet.org/xsd/adlcp_rootv1p2"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.imsproject.org/xsd/imscp_rootv1p1p2 imscp_rootv1p1p2.xsd
  http://www.adlnet.org/xsd/adlcp_rootv1p2 adlcp_rootv1p2.xsd">
  <metadata>
    <schema>ADL SCORM</schema>
    <schemaversion>1.2</schemaversion>
  </metadata>
  <organizations default="studybeats_org">
    <organization identifier="studybeats_org">
      <title>${safeTitle} — StudyBeats</title>
      <item identifier="item_1" identifierref="resource_1">
        <title>${safeTitle}</title>
      </item>
    </organization>
  </organizations>
  <resources>
    <resource identifier="resource_1" type="webcontent" adlcp:scormtype="sco" href="index.html">
      <file href="index.html"/>
    </resource>
  </resources>
</manifest>`;
}

function generateSCORMHtml(song: Song) {
  const lyrics = (song.generated_lyrics || "").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  const text = (song.original_text || "").replace(/</g, "&lt;").replace(/>/g, "&gt;");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${song.title} — StudyBeats</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #0a0a0f; color: #f5f5f5; min-height: 100vh; padding: 2rem; }
    .container { max-width: 800px; margin: 0 auto; }
    h1 { font-size: 2rem; margin-bottom: 0.5rem; background: linear-gradient(135deg, #8b5cf6, #3b82f6); -webkit-background-clip: text; -webkit-text-fill-color: transparent; }
    .badge { display: inline-block; background: rgba(139,92,246,0.15); color: #a78bfa; padding: 0.25rem 0.75rem; border-radius: 999px; font-size: 0.75rem; margin-bottom: 1.5rem; text-transform: capitalize; }
    .section { background: rgba(255,255,255,0.04); border: 1px solid rgba(255,255,255,0.08); border-radius: 1rem; padding: 1.5rem; margin-bottom: 1.5rem; }
    .section h2 { font-size: 1.1rem; margin-bottom: 1rem; color: #a78bfa; }
    .section p, .section pre { font-size: 0.9rem; line-height: 1.7; color: rgba(245,245,245,0.8); white-space: pre-wrap; }
    .footer { text-align: center; margin-top: 2rem; font-size: 0.75rem; color: rgba(245,245,245,0.3); }
    .footer a { color: #8b5cf6; text-decoration: none; }
  </style>
  <script>
    // SCORM 1.2 API adapter
    var API = null;
    function findAPI(win) {
      try {
        while (win.API == null && win.parent != null && win.parent != win) { win = win.parent; }
        return win.API;
      } catch (e) { return null; }
    }
    function initSCORM() {
      API = findAPI(window);
      if (API) { API.LMSInitialize(""); API.LMSSetValue("cmi.core.lesson_status", "completed"); API.LMSCommit(""); }
    }
    function exitSCORM() { if (API) { API.LMSFinish(""); } }
    window.onload = initSCORM;
    window.onbeforeunload = exitSCORM;
  </script>
</head>
<body>
  <div class="container">
    <h1>${song.title}</h1>
    <span class="badge">${song.style}${song.subject ? ` · ${song.subject}` : ""}</span>
    
    <div class="section">
      <h2>📝 Original Notes</h2>
      <pre>${text}</pre>
    </div>
    
    <div class="section">
      <h2>🎵 Generated Lyrics</h2>
      <pre>${lyrics}</pre>
    </div>
    
    <div class="footer">
      <p>Generated by <a href="https://learn-jams.lovable.app" target="_blank">StudyBeats</a> · Music-based memorization</p>
    </div>
  </div>
</body>
</html>`;
}

export default function Export() {
  const { t } = useTranslation();
  usePageSEO({ title: t("export.title", "LMS Export") + " — StudyBeats", description: t("export.subtitle", "Generate SCORM packages for LMS"), noindex: true });
  const { user } = useAuth();
  const navigate = useNavigate();

  const [songs, setSongs] = useState<Song[]>([]);
  const [loading, setLoading] = useState(true);
  const [exporting, setExporting] = useState<string | null>(null);

  useEffect(() => {
    if (!user) return;
    const fetch = async () => {
      const { data } = await supabase
        .from("songs")
        .select("id, title, style, original_text, generated_lyrics, status, subject")
        .eq("user_id", user.id)
        .eq("status", "ready")
        .order("created_at", { ascending: false });
      setSongs((data as Song[]) || []);
      setLoading(false);
    };
    fetch();
  }, [user]);

  const handleExport = async (song: Song) => {
    setExporting(song.id);
    try {
      const zip = new JSZip();
      zip.file("imsmanifest.xml", generateSCORMManifest(song));
      zip.file("index.html", generateSCORMHtml(song));

      const blob = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${song.title.replace(/[^a-zA-Z0-9]/g, "_")}_SCORM.zip`;
      a.click();
      URL.revokeObjectURL(url);
      toast.success(t("export.success", "SCORM package downloaded!"));
    } catch (err: any) {
      toast.error(err.message || t("export.error", "Export failed"));
    } finally {
      setExporting(null);
    }
  };

  return (
    <div className="min-h-screen bg-background relative overflow-hidden">
      <div className="fixed inset-0 pointer-events-none bg-[radial-gradient(ellipse_80%_50%_at_50%_-20%,hsl(var(--primary)/0.08),transparent_70%)]" />
      <Navbar />

      <div className="container mx-auto pt-28 pb-16 px-4 max-w-4xl relative z-10">
        <Button variant="ghost" size="sm" onClick={() => navigate(-1)} className="gap-2 mb-6 rounded-xl text-muted-foreground">
          <ArrowLeft className="w-4 h-4" /> {t("common.back", "Back")}
        </Button>

        <motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7, ease }} className="text-center mb-12">
          <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-emerald-500 to-teal-600 flex items-center justify-center mx-auto mb-5 shadow-lg shadow-emerald-500/20">
            <BookOpen className="w-8 h-8 text-primary-foreground" />
          </div>
          <h1 className="font-display text-4xl md:text-5xl font-bold tracking-tight mb-3">{t("export.title", "LMS Export")}</h1>
          <p className="text-muted-foreground text-lg max-w-xl mx-auto">{t("export.subtitle", "Generate SCORM packages from your StudyBeats for uploading to university learning platforms")}</p>
        </motion.div>

        {/* Info card */}
        <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1, ease }} className="glass-card-elevated p-6 mb-8 flex items-start gap-4 max-w-2xl mx-auto">
          <FileArchive className="w-6 h-6 text-emerald-500 shrink-0 mt-0.5" />
          <div>
            <h3 className="font-semibold text-sm mb-1">{t("export.scorm_info_title", "SCORM 1.2 Package")}</h3>
            <p className="text-sm text-muted-foreground leading-relaxed">
              {t("export.scorm_info", "Each export generates a SCORM 1.2 compatible ZIP file containing the original notes and generated lyrics. Upload it to Moodle, Canvas, Blackboard, or any SCORM-compatible LMS.")}
            </p>
          </div>
        </motion.div>

        {loading ? (
          <div className="flex justify-center py-20"><Loader2 className="w-8 h-8 text-primary animate-spin" /></div>
        ) : songs.length === 0 ? (
          <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="text-center py-16">
            <Music className="w-16 h-16 text-muted-foreground/20 mx-auto mb-4" />
            <h3 className="font-display text-xl font-semibold mb-2">{t("export.no_songs", "No songs to export")}</h3>
            <p className="text-muted-foreground mb-6">{t("export.no_songs_text", "Create a song first, then come back to export it")}</p>
            <Button className="gradient-bg-premium gap-2 rounded-xl" onClick={() => navigate("/create")}>
              <Music className="w-4 h-4" /> {t("export.create", "Create a song")}
            </Button>
          </motion.div>
        ) : (
          <div className="space-y-3 max-w-2xl mx-auto">
            {songs.map((song, i) => (
              <motion.div
                key={song.id}
                initial={{ opacity: 0, y: 12 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.04 }}
                className="glass-card p-5 flex items-center gap-4"
              >
                <div className="w-11 h-11 rounded-xl bg-gradient-to-br from-primary/15 to-secondary/15 flex items-center justify-center shrink-0">
                  <Music className="w-5 h-5 text-primary" />
                </div>
                <div className="flex-1 min-w-0">
                  <h4 className="font-semibold text-sm truncate">{song.title}</h4>
                  <p className="text-xs text-muted-foreground capitalize">{song.style}{song.subject ? ` · ${song.subject}` : ""}</p>
                </div>
                <Button
                  size="sm"
                  variant="outline"
                  className="gap-2 rounded-xl shrink-0"
                  onClick={() => handleExport(song)}
                  disabled={exporting === song.id}
                >
                  {exporting === song.id ? (
                    <Loader2 className="w-3.5 h-3.5 animate-spin" />
                  ) : (
                    <Download className="w-3.5 h-3.5" />
                  )}
                  SCORM
                </Button>
              </motion.div>
            ))}
          </div>
        )}
      </div>
      <Footer />
    </div>
  );
}
